PR#1
beeonkaa9/react-tic-tac-toe pull request #1
Opened 2021-11-22 17:47 UTC by beeonkaa9

2021-11-22 20:51 UTC, Idonoghue reviewed
Awesome job! I really like the way you organized the project. All of the React components make sense and are written simply making it very easy to read and understand. 👍

2021-11-22 20:51 UTC, Idonoghue commented on src/App.css
> +  background-color: lightskyblue;
nice hover styles! You could also add `cursor: pointer` to these clickable elements

2021-11-22 20:51 UTC, Idonoghue commented on src/App.tsx
> +    <>
You don't need this fragment. These are usually only needed if you want to have 2 or more components share the top level JSX of a react component but in this case you only have 1 div at the top level of this component.

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +  const [boardState, setBoardState] = useState([
This might be better named as `boardStates` or maybe even gameState or gameHistory? When I first saw it I assumed it was just a single board state not an array of states representing the entire history.
```suggestion
  const [boardStates, setBoardStates] = useState([
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +  const [playerOne, setPlayerOne] = useState(true)
I would also consider a more informative name here as well. Names go a _long_ way in improving code readability
```suggestion
  const [isPlayerOnesTurn, setIsPlayerOnesTurn] = useState(true)
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +              handleTurn={(index) => handleTurn(index)}
the `handleTurn` function is only used in one place. I don't think it is worth being declared separately. Instead you can define the function here inline.
```suggestion
              handleTurn={(index) => {... put the body of handleTurn in here}}
```

The advantages to this is that we don't clutter the component with a reusable function in the body and we don't need to annotate the type of input parameters like `index`.

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +      return board[index]
This if is just to prevent game logic if we are already in a win state. You don't need to return anything here
```suggestion
      return
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +    setBoardState([...boardState, { board: board }])
Very clean! just a few minor syntax touchups you can do. 

Also I think this is what Isaiah meant by wanting this to be a pure function. You are mutating a variable (`board`) that is declared outside the scope of the function. While this code works trust me when I say that this pattern leads to a world of hurt and pain as it can cause really weird state bugs.

To skirt around that just declare board as an internal variable of the function.

PS `[...arr]` does the same thing as `.slice(0)` in doing a copy by value instead of by reference.
```suggestion
    const board = [...boardState[boardState.length - 1].board]
    
    setTurn(turn + 1)

    board[index] = playerOne ? 'X' : 'O'

    setPlayerOne(!playerOne)

    setBoardState([...boardState, { board }])
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +  const winner = determineWin(board)
I think we can cut all of these variables here except `board`. `winner` is only used by the `Status` component which already gets the whole board. It can just call `determineWin(board)` internally to determine the winner. No need have a `winner` prop. 
```suggestion
    const board = [ ...boardState[boardState.length - 1].board ] // or boardState[boardState.length - 1].board.slice(0) if you like
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +    setBoardState([...newBoard])
You can add a little syntax sugar here as well
```suggestion
    setTurn(turn)
    setPlayerOne(turn % 2 === 0)

    setBoardState(boardState.slice(0, turn + 1))
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Board.tsx
> +          <Moves boardState={boardState} changeTurn={changeTurn} />
I would also inline changeTurn here because it isn't a reusable function. I like leaning towards inline functions too because it closely connects a React component with the logic of the function it is receiving.

Another minor point, you don't have to do this but typically callback function props begin with `on___`
```suggestion
          <Moves boardState={boardState} onTurnChange={(turn) => {... function goes here}} />
```

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Status.tsx
> +  const isFullBoard = board.every((square) => square === 'X' || square === 'O')
nice use of `every`!

2021-11-22 20:51 UTC, Idonoghue commented on src/components/Status.tsx
> +  )
This is could be _slightly_ more declarative rewritten a little. If you check for winner first it just simplifies it a bit.
```suggestion
  return (
    <h1>
      {winner
        ? `Player ${
            winner === 'X' ? 1 : 2
          } wins! Click "Reset game" to play again`
        : isFullBoard
        ? 'Player 1 and 2 tied! Click "Reset game" to play again'
        : `Player ${player}'s turn`}
    </h1>
  )
```

2021-11-22 20:51 UTC, Idonoghue commented on src/utils/determineWin.tsx
> +  }
Nice approach to this problem! You could also make this more declarative by avoiding a for loop. tbh this took me a lot of thinking to figure out but in the end I think it makes sense. We are _reducing_ a 2D array of possibleWins to a string of '' | 'X' | 'O'
```suggestion
  return possibleWins.reduce(
    (acc, [a, b, c]) =>
      board[a] && board[a] === board[b] && board[a] === board[c]
        ? board[a]
        : acc,
    ''
  )
```

2021-11-23 17:20 UTC, hector16 requested changes
I would suggest changing all of your function components to be Arrow Functions everything else seems fine though!

2021-11-29 20:56 UTC, merged